apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-backend
  template:
    metadata:
      labels:
        app: springboot-backend
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: backend
        image: 878445923393.dkr.ecr.us-east-1.amazonaws.com/task-backend:aws-v1
        ports:
        - containerPort: 8080
        # Attention ici : envFrom et env sont alignés avec ports
        envFrom:
        - configMapRef:
            name: db-config  
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort  
  selector:
    app: springboot-backend
  ports:
    - port: 8080
      targetPort: 8080
